CFE_episodes: 1
RTH: 200000
SNR: 10
algorithm_path: agents.vdn.VDNAgent
base_config:
- ./env.yaml
- configs/base_configs/vdn.yaml
batch_size: 32
buffer_capacity: 5000
burnin_episode: 1000
env_battery_capacity: 100
env_collide_range: 1
env_comm_range: 10
env_enable_charger: false
env_enable_obstacle: false
env_major_point_min_distant_percent: 0.25
env_num_agent: 10
env_num_charger: 3
env_num_circle_obstacle: 1
env_num_grid: 50
env_num_major_point: 3
env_num_max_neighbor_agent: 5
env_num_max_neighbor_poi: 10
env_num_poi: 100
env_num_rect_obstacle: 1
env_observation_test: true
env_static_poi: false
env_suofang: 10
env_theta: 60
env_use_pixel_obs: true
env_use_square_obs: false
env_zmax: 15
env_zmin: 5
episode_length: 100
epsilon_decay_percent_episode: 0.0001
epsilon_decay_temperature: 0.0001
epsilon_exponential_decay: false
epsilon_linear_decay: true
gamma: 0.99
grad_norm_clip: 10.0
hidden_dim: 128
initial_epsilon: 1.0
learning_rate: 0.0005
max_poi_speed: 0
min_epsilon: 0.05
num_episodes: 20000
num_max_keep_ckpt: 5
outage_probability: 0
scenario_path: scenarios.continuous_mcs3D.ContinuousMCS3D
soft_update_target_network: true
step_episode_length: 100
target_update_interval: 200
tau: 0.01
testing_action_mode: greedy
testing_episodes: 20
testing_interval: 100
trainer_path: trainers.vdn_trainer.VDNTrainer
training_action_mode: epsilon-greedy
training_interval: 1
training_times: 4
user_episode_length: 100
user_episodes: 10
work_dir: checkpoints/vdn
