scenario_path: scenarios.continuous_mcs3D.ContinuousMCS3D

# Environment Configuration
#Divide the 200200 grid, each grid size is 5m5m, the range is 1000*1000m, and each grid can have multiple agents and POIs# 40 5 30
env_num_grid: 50
env_suofang: 10
env_num_agent: 10
env_num_poi: 100
env_num_major_point: 3
env_major_point_min_distant_percent: 0.25
#Up to 20 grids 5m = 100m
env_zmax: 15
#10*5m=50m
env_zmin: 5
max_poi_speed: 0
#env_coverage_range: 3
#env_observe_range_max: 4  # 10=>13=>16=>19=>22=>25
#The communication range is 2 squares
env_comm_range: 10
#1 squares
env_collide_range: 1
SNR: 10
outage_probability: 0
env_theta: 60

env_enable_obstacle: false
env_num_rect_obstacle: 1
env_num_circle_obstacle: 1

env_use_pixel_obs: true
env_use_square_obs: false

env_static_poi: false

env_num_max_neighbor_agent: 5
env_num_max_neighbor_poi: 10

env_enable_charger: false
env_num_charger: 3
#env_battery_capacity: 1500000
env_battery_capacity: 100
env_observation_test: true

#wireness_communication
RTH: 200000 #200kbit/s

#Energy consumption
#PR: 1
#P0: 99.66
#P1: 120.16
#Utip: 120
#v0: 0.02
#d0: 0.48
#rho: 1.225
#s0: 0.0001
#A: 0.5
#Erx: 0.01


# Training hyper-params
num_episodes: 30000
episode_length: 100
training_interval: 1
training_times: 4
testing_interval: 100
testing_episodes: 20
CFE_episodes: 1
step_episode_length: 100
user_episodes: 10
user_episode_length: 100
