# Independent PPO (IPPO) base config
# exp_name: ippo_exp
algorithm_path: agents.ippo.IPPOAgent
trainer_path: trainers.ippo_trainer.IPPOTrainer

# environment
env_num_agent: 4
env_num_poi: 6
episode_length: 200

# training
num_episodes: 20000
training_interval: 1
testing_interval: 100
testing_episodes: 5

learning_rate: 3e-4
gamma: 0.99
gae_lambda: 0.95
ppo_epochs: 4
batch_size: 64
clip_param: 0.2
entropy_coef: 0.01
value_loss_coef: 0.5
grad_norm_clip: 0.5
normalize_advantages: True

hidden_dim: 128

num_max_keep_ckpt: 5
log_dir: tb
