CFE_episodes: 1
RTH: 200000
SNR: 10
algorithm_path: agents.mappo.MAPPOAgent
base_config:
- ./env.yaml
- configs/base_configs/mappo.yaml
batch_size: 32
clip_param: 0.2
entropy_coef: 0.01
env_battery_capacity: 100
env_collide_range: 1
env_comm_range: 10
env_enable_charger: false
env_enable_obstacle: false
env_major_point_min_distant_percent: 0.25
env_num_agent: 10
env_num_charger: 3
env_num_circle_obstacle: 1
env_num_grid: 50
env_num_major_point: 3
env_num_max_neighbor_agent: 5
env_num_max_neighbor_poi: 10
env_num_poi: 100
env_num_rect_obstacle: 1
env_observation_test: true
env_static_poi: false
env_suofang: 10
env_theta: 60
env_use_pixel_obs: true
env_use_square_obs: false
env_zmax: 15
env_zmin: 5
episode_length: 100
gae_lambda: 0.95
gamma: 0.99
grad_norm_clip: 10.0
hidden_dim: 128
learning_rate: 0.0001
max_poi_speed: 0
normalize_advantages: true
num_episodes: 30000
num_max_keep_ckpt: 5
outage_probability: 0
ppo_epochs: 2
scenario_path: scenarios.continuous_mcs3D.ContinuousMCS3D
step_episode_length: 100
testing_action_mode: greedy
testing_episodes: 20
testing_interval: 100
trainer_path: trainers.mappo_trainer.MAPPOTrainer
training_action_mode: sample
training_interval: 1
training_times: 4
user_episode_length: 100
user_episodes: 10
value_loss_coef: 1.0
work_dir: checkpoints/mappo-0128
